# Generated by Django 5.1.4 on 2026-06-22 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('formal_name', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ocm_connection_type_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('icon_name', models.CharField(blank=True, default='plug', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('comment', models.TextField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, default='')),
                ('is_private', models.BooleanField(default=False)),
                ('ocm_operator_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='ukcharge_op_name_131663_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocm_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('slug', models.SlugField(blank=True, default='', max_length=600)),
                ('lat', models.FloatField(db_index=True)),
                ('lon', models.FloatField(db_index=True)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('town', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=255)),
                ('postcode', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('country', models.CharField(db_index=True, default='GB', max_length=100)),
                ('country_code', models.CharField(default='GB', max_length=5)),
                ('operator_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('connection_type', models.CharField(blank=True, default='', max_length=255)),
                ('connector_types', models.JSONField(blank=True, default=list)),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('number_of_points', models.IntegerField(default=1)),
                ('usage_type', models.CharField(blank=True, default='', max_length=255)),
                ('access_type', models.CharField(blank=True, default='', max_length=255)),
                ('cost_type', models.CharField(blank=True, default='', max_length=255)),
                ('usage_cost', models.CharField(blank=True, default='', max_length=500)),
                ('is_live_status', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('out_of_service', 'Out of Service'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=50)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('ocm_data', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('connector_ids', models.ManyToManyField(blank=True, to='ukcharge.connectortype')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ukcharge.operator')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status'], name='ukcharge_ch_status_a05795_idx'), models.Index(fields=['power_kw'], name='ukcharge_ch_power_k_c5295b_idx'), models.Index(fields=['operator_name'], name='ukcharge_ch_operato_7c18f7_idx'), models.Index(fields=['town'], name='ukcharge_ch_town_4d476d_idx'), models.Index(fields=['postcode'], name='ukcharge_ch_postcod_4d03ba_idx'), models.Index(fields=['country'], name='ukcharge_ch_country_692d68_idx'), models.Index(fields=['is_live_status'], name='ukcharge_ch_is_live_2d0553_idx'), models.Index(fields=['lat', 'lon'], name='ukcharge_ch_lat_5e53d7_idx')],
            },
        ),
    ]
